name: Convert STEP to PNG

on:
  workflow_dispatch:

jobs:
  mayo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libfuse2 -y
          wget -O ./mayo.AppImage https://github.com/fougue/mayo/releases/download/v0.7.0/Mayo-0.7.0.1113-f88a35d-x86_64.AppImage
          chmod a+x mayo.AppImage
      
      - name: Run Mayo
        run: |
          ./mayo.AppImage docs/DCDC-FusePCB.step -e docs/DCDC-FusePCB.stl
          timeout 10s ./mayo.AppImage docs/DCDC-FusePCB.step -e docs/DCDC-FusePCB.png || true
          rm mayo.AppImage
          
      - name: Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory '*'
          git add .
          git commit -m "Updated PCB .png"
          git push
          
