name: Convert STEP to PNG

on:
  workflow_dispatch:

jobs:
  f3d:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Dependencis
        run: |
          sudo apt update
          sudo apt install xvfb libopengl0
          sudo mkdir -p /usr/local/f3d
          cd /usr/local/f3d
          sudo wget -O "./f3d.tar.gz" https://github.com/f3d-app/f3d/releases/download/v2.3.0/F3D-2.3.0-Linux-x86_64-raytracing.tar.gz
          sudo tar -xzf "f3d.tar.gz" -C "./" --strip-components=1

      - name: Start Xvfb
        run: Xvfb :1 -screen 0 1024x768x16 -noreset -nolisten tcp &
      
      - name: Run f3d with Xvfb
        run: |
          export DISPLAY=:1
          /usr/local/f3d/bin/f3d
          xwd -root -display :1 | convert xwd:- docs/screenshot.png
          /usr/local/f3d/bin/f3d "docs/DCDC-FusePCB.step" --output "docs/test.png" --verbose

      - name: Push Changes
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit. Exiting."
            exit 0
          else
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global --add safe.directory '*'
            git add .
            git commit -m "Updated PCB .png"
            git push
          fi
          
