name: Convert STEP to PNG

on:
  workflow_dispatch:

jobs:
  f3d:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install f3d
        run: |
          sudo apt-get install libgles2-mesa -y
          sudo mkdir -p /usr/local/f3d
          sudo wget -O "/usr/local/f3d/f3d.deb" https://github.com/f3d-app/f3d/releases/download/v2.3.0/F3D-2.3.0-Linux-x86_64-headless.deb
          sudo dpkg -i f3d.deb

      - name: Generate .png
        run: |
          f3d "docs/DCDC-FusePCB.step" --output "docs/test.png" --verbose

      - name: Push Changes
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit. Exiting."
            exit 0
          else
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global --add safe.directory '*'
            git add .
            git commit -m "Updated PCB .png"
            git push
          fi
          
