# TODO: conflict resolution when pushing
# TODO: refactor directories, kicad version, etc with ENV vars

name: Export KiCAD Files

on:
  push:
    branches:
      - 'main'
    paths:
      - '*.kicad_pcb'
      - '*.kicad_sch'

  workflow_dispatch:

jobs:
    kicad-mayo-docker:
      if: ${{ github.actor != 'github-actions[bot]' }}
      
      runs-on: ubuntu-latest
        
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Install Dependencies
          run: |
            sudo add-apt-repository ppa:kicad/kicad-7.0-releases
            sudo apt-get update
            sudo apt-get install xvfb wget libfuse2 -y
            wget -O ./mayo.AppImage https://github.com/fougue/mayo/releases/download/v0.8.0/Mayo-0.8.0-x86_64.AppImage
            chmod a+x mayo.AppImage

        - name: Clone Submodule
          run: |
            git clone https://github.com/lhr-solar/UTSVT-KiCadLibraries.git

        - name: Checkout Submodule Branch
          run: |
            cd UTSVT-KiCadLibraries
            git checkout DCDC-FusePCB
            cd ..
        
        - name: Create Docs Directory
          run: |
            DIR="docs"
            if [ ! -d "$DIR" ]; then
              mkdir "$DIR"
            fi
            
        - name: Process PCB Files
          run: |
            for i in *.kicad_pcb; do
              [ -f "$i" ] || break
              BASE_NAME="$(echo $i | rev | cut -d '/' -f 1 | rev | cut -d '.' -f 1)"
              kicad-cli pcb export step --subst-models -o "docs/$BASE_NAME.step" "$i"
              # kicad-cli pcb export pdf --ibt --ev --erd -o "docs/$BASE_NAME (PCB).pdf" "$i"
            done
            
        - name: Process SCH Files
          run: |
            for i in *.kicad_sch; do
              [ -f "$i" ] || break
              BASE_NAME="$(echo $i | rev | cut -d '/' -f 1 | rev | cut -d '.' -f 1)"
              kicad-cli sch export pdf -o "docs/$BASE_NAME.pdf" "$i"
            done

        - name: Process STEP Outputs
          env:
            DISPLAY: :0
          run: |
            Xvfb $DISPLAY -screen 0 1280x1024x24 &
            sleep 5s
            ./mayo.AppImage docs/DCDC-FusePCB.step -e docs/DCDC-FusePCB.stl
            ./mayo.AppImage -s ".github/workflows/mayo-config.ini" docs/DCDC-FusePCB.step -e docs/DCDC-FusePCB.png

        - name: Remove Dependencies
          run: |
            rm mayo.AppImage
            
        - name: Push Changes
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global --add safe.directory '*'
            git add .
            git commit -m "Updated Exports"
            git push
