name: Test Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: parthivs20/kicad-exporter@v1.0
        with:
          out-files: |
            png
            stl
            step
